= HBase Indexer

The HBase Indexer allows you to easily and quickly index HBase rows into Solr.

This uses HBase replication to copy rows from HBase to the Solr index in real-time.

// Usage documentation can be found on the hbase-indexer Wiki - http://github.com/NGDATA/hbase-indexer/wiki.

== Features of the Lucidworks hbase-indexer

This project is a fork of the original http://github.com/NGDATA/hbase-indexer[hbase-indexer] from NGDATA, with these additional features:

* Support for HBase 0.94, 0.96, 0.98, 1.1.0 and 1.1.2
* Support for Solr 5.x (Solr 6.x to come soon)
* Kerberos authentication
* Output to Lucidworks Fusion pipelines (optional)

IMPORTANT: Due to the changes required for Solr 5.x support, builds from this fork will not work with Solr 4.x.

== Subprojects

=== HBase SEP

A standalone library for asynchronously processing HBase mutation events by hooking into HBase replication, see <<hbase-sep/README.md,the SEP readme>>.

=== HBase SEP & replication monitoring

A standalone utility to monitor HBase replication progress, see <<hbase-sep/hbase-sep-tools/README.md, the SEP-tools readme>>.

== How to Build

=== Building for General Use

You can build the full hbase-indexer project as follows:

    mvn clean install -DskipTests

// **The profile 0.98, 0.96, 0.94 cannot be used at the moment since the code was modified to work with HBase 1.1.0**

The default build is linked to HBase 0.94. In order to build for HBase 0.98, run the following command:

    mvn clean install -DskipTests -Dhbase.api=0.98

To build for HBase 1.1.0, run the following command:

    mvn clean install -DskipTests -Dhbase.api=1.1.0


==== Building Hortonworks Version

In order to build the full hbase-indexer project with an specific version of Hortonworks.

      mvn clean package -Pdist -DskipTests -Dhbase.api=1.1.2 -Dhdp.version=".2.4.2.0-258"

**The profile 1.1.2 can be used with the hdp version suffix. (`-Dhdp.version`)**
